# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dac_module.proto
"""Generated protocol buffer code."""
# pylint: skip-file
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from edgepi.eeprom.protobuf_assets.generated_pb2 import calibration_parameters_pb2 as calibration__parameters__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64\x61\x63_module.proto\x1a\x1c\x63\x61libration_parameters.proto\"\x93\x03\n\tDacModule\x12\"\n\x08\x64\x61\x63_ch_1\x18\x01 \x01(\x0b\x32\x0b.CalibParamH\x00\x88\x01\x01\x12\"\n\x08\x64\x61\x63_ch_2\x18\x02 \x01(\x0b\x32\x0b.CalibParamH\x01\x88\x01\x01\x12\"\n\x08\x64\x61\x63_ch_3\x18\x03 \x01(\x0b\x32\x0b.CalibParamH\x02\x88\x01\x01\x12\"\n\x08\x64\x61\x63_ch_4\x18\x04 \x01(\x0b\x32\x0b.CalibParamH\x03\x88\x01\x01\x12\"\n\x08\x64\x61\x63_ch_5\x18\x05 \x01(\x0b\x32\x0b.CalibParamH\x04\x88\x01\x01\x12\"\n\x08\x64\x61\x63_ch_6\x18\x06 \x01(\x0b\x32\x0b.CalibParamH\x05\x88\x01\x01\x12\"\n\x08\x64\x61\x63_ch_7\x18\x07 \x01(\x0b\x32\x0b.CalibParamH\x06\x88\x01\x01\x12\"\n\x08\x64\x61\x63_ch_8\x18\x08 \x01(\x0b\x32\x0b.CalibParamH\x07\x88\x01\x01\x42\x0b\n\t_dac_ch_1B\x0b\n\t_dac_ch_2B\x0b\n\t_dac_ch_3B\x0b\n\t_dac_ch_4B\x0b\n\t_dac_ch_5B\x0b\n\t_dac_ch_6B\x0b\n\t_dac_ch_7B\x0b\n\t_dac_ch_8b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dac_module_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DACMODULE._serialized_start=51
  _DACMODULE._serialized_end=454
# @@protoc_insertion_point(module_scope)
