# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rtd_module.proto
"""Generated protocol buffer code."""
# pylint: skip-file
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from edgepi.eeprom.protobuf_assets.generated_pb2 import calibration_parameters_pb2 as calibration__parameters__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10rtd_module.proto\x1a\x1c\x63\x61libration_parameters.proto\"^\n\tRtdModule\x12\x1d\n\x03rtd\x18\x01 \x01(\x0b\x32\x0b.CalibParamH\x00\x88\x01\x01\x12\x19\n\x0crtd_resistor\x18\x02 \x01(\x02H\x01\x88\x01\x01\x42\x06\n\x04_rtdB\x0f\n\r_rtd_resistorb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rtd_module_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RTDMODULE._serialized_start=50
  _RTDMODULE._serialized_end=144
# @@protoc_insertion_point(module_scope)
