# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tc_module.proto
"""Generated protocol buffer code."""
# pylint: skip-file
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from edgepi.eeprom.protobuf_assets.generated_pb2 import calibration_parameters_pb2 as calibration__parameters__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftc_module.proto\x1a\x1c\x63\x61libration_parameters.proto\"\xd2\x02\n\x08TcModule\x12\x1e\n\x04tc_B\x18\x01 \x01(\x0b\x32\x0b.CalibParamH\x00\x88\x01\x01\x12\x1e\n\x04tc_E\x18\x02 \x01(\x0b\x32\x0b.CalibParamH\x01\x88\x01\x01\x12\x1e\n\x04tc_J\x18\x03 \x01(\x0b\x32\x0b.CalibParamH\x02\x88\x01\x01\x12\x1e\n\x04tc_K\x18\x04 \x01(\x0b\x32\x0b.CalibParamH\x03\x88\x01\x01\x12\x1e\n\x04tc_N\x18\x05 \x01(\x0b\x32\x0b.CalibParamH\x04\x88\x01\x01\x12\x1e\n\x04tc_R\x18\x06 \x01(\x0b\x32\x0b.CalibParamH\x05\x88\x01\x01\x12\x1e\n\x04tc_S\x18\x07 \x01(\x0b\x32\x0b.CalibParamH\x06\x88\x01\x01\x12\x1e\n\x04tc_T\x18\x08 \x01(\x0b\x32\x0b.CalibParamH\x07\x88\x01\x01\x42\x07\n\x05_tc_BB\x07\n\x05_tc_EB\x07\n\x05_tc_JB\x07\n\x05_tc_KB\x07\n\x05_tc_NB\x07\n\x05_tc_RB\x07\n\x05_tc_SB\x07\n\x05_tc_Tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tc_module_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TCMODULE._serialized_start=50
  _TCMODULE._serialized_end=388
# @@protoc_insertion_point(module_scope)
