# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: adc_module.proto
"""Generated protocol buffer code."""
# pylint: skip-file

from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from edgepi.eeprom.proto_files import calibration_parameters_pb2 as calibration__parameters__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61\x64\x63_module.proto\x1a\x1c\x63\x61libration_parameters.proto\"\xf3\x04\n\tAdcModule\x12#\n\x08\x61\x64\x63_ch_1\x18\x01 \x01(\x0b\x32\x0c.calib_paramH\x00\x88\x01\x01\x12#\n\x08\x61\x64\x63_ch_2\x18\x02 \x01(\x0b\x32\x0c.calib_paramH\x01\x88\x01\x01\x12#\n\x08\x61\x64\x63_ch_3\x18\x03 \x01(\x0b\x32\x0c.calib_paramH\x02\x88\x01\x01\x12#\n\x08\x61\x64\x63_ch_4\x18\x04 \x01(\x0b\x32\x0c.calib_paramH\x03\x88\x01\x01\x12#\n\x08\x61\x64\x63_ch_5\x18\x05 \x01(\x0b\x32\x0c.calib_paramH\x04\x88\x01\x01\x12#\n\x08\x61\x64\x63_ch_6\x18\x06 \x01(\x0b\x32\x0c.calib_paramH\x05\x88\x01\x01\x12#\n\x08\x61\x64\x63_ch_7\x18\x07 \x01(\x0b\x32\x0c.calib_paramH\x06\x88\x01\x01\x12#\n\x08\x61\x64\x63_ch_8\x18\x08 \x01(\x0b\x32\x0c.calib_paramH\x07\x88\x01\x01\x12%\n\nadc_diff_1\x18\t \x01(\x0b\x32\x0c.calib_paramH\x08\x88\x01\x01\x12%\n\nadc_diff_2\x18\n \x01(\x0b\x32\x0c.calib_paramH\t\x88\x01\x01\x12%\n\nadc_diff_3\x18\x0b \x01(\x0b\x32\x0c.calib_paramH\n\x88\x01\x01\x12%\n\nadc_diff_4\x18\x0c \x01(\x0b\x32\x0c.calib_paramH\x0b\x88\x01\x01\x42\x0b\n\t_adc_ch_1B\x0b\n\t_adc_ch_2B\x0b\n\t_adc_ch_3B\x0b\n\t_adc_ch_4B\x0b\n\t_adc_ch_5B\x0b\n\t_adc_ch_6B\x0b\n\t_adc_ch_7B\x0b\n\t_adc_ch_8B\r\n\x0b_adc_diff_1B\r\n\x0b_adc_diff_2B\r\n\x0b_adc_diff_3B\r\n\x0b_adc_diff_4b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'adc_module_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADCMODULE._serialized_start=51
  _ADCMODULE._serialized_end=678
# @@protoc_insertion_point(module_scope)
