# This workflow will build and publish the package to PyPI upon push or merge to main branch
# and then create a GitHub release based on latest release tag

name: Build and Release

on:
  push:
    tags:
      - release/*  

jobs:
  build-and-publish:
    name: Publish to PyPi and Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements_build.txt ]; then python -m pip install -r requirements_build.txt; fi
    - name: Build Package
      run: |
        python -m build
    - name: Publish Package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.9.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Release Package
      uses: ncipollo/release-action@v1.12.0
