# This workflow will install Python dependencies, run tests using PyTest.

# name: PyTest Integration Test

# on:
#   push:
#     branches:
#       - 'staging'
#   pull_request:
#     branches:
#       - 'staging'

# jobs:
#   test:
#     name: Self-Hosted Integration Test
#     runs-on: self-hosted

#     steps:
#     - name: Checkout
#       uses: actions/checkout@v3
#     - name: Install Dependencies
#       run: |
#         python3 -m pip install --upgrade pip
#         python3 -m venv venv_test
#         source venv_test/bin/activate
#         if [ -f requirements_test.txt ]; then pip install -r requirements_test.txt; fi
#     - name: Test with pytest
#       run: |
#         source venv_test/bin/activate
#         cd src/
#         pytest ../tests/integration_tests
