# This workflow will install Python dependencies, run tests using PyTest.

name: PyTest Integration Test

on:
  push:
    branches:
      - 'integration-test-implement'
  pull_request:
    branches:
      - 'integration-test-implement'

jobs:
  test:
    name: Integration Tests
    runs-on: [self-hosted, linux, ARM64, integration]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test with pytest
        run: |
          pwd
          source venv_test/bin/activate
          pip install -r requirements_test.txt
          cd src/
          python -m pytest ../tests/integration_tests
      # python -m pytest ../tests/integration_tests --cov --cov-report=xml
      # - name: Code Coverage Summary Report
      #   uses: irongut/CodeCoverageSummary@v1.2.0
      #   with:
      #     filename: test_cov/coverage.xml
      #     badge: true
      #     format: markdown
      #     hide_complexity: true
      #     indicators: true
      #     output: both
      # - name: Add Coverage PR Comment
      #   uses: marocchino/sticky-pull-request-comment@v2
      #   with:
      #     recreate: true
      #     path: code-coverage-results.md
